# Default ScopeBuddy profile

# -- Global environment variables --

# Proton
export PROTON_FSR4_UPGRADE=1

# MangoHUD
export MANGOHUD=1
export MANGOHUD_CONFIG="fps_only,fps_limit=171"

# Misc
export XKB_DEFAULT_LAYOUT=fr

# -- Gamescope configuration --
SCB_GAMESCOPE_ARGS="-f -w 3840 -h 2160 -r 180 --adaptive-sync"
SCB_AUTO_RES=0
SCB_AUTO_HDR=0
SCB_AUTO_VRR=0
