# Default ScopeBuddy profile

# - Global environment variables -
#export XKB_DEFAULT_LAYOUT=no
#export MANGOHUD_CONFIG=preset=2

# - Default Gamescope configuration -
SCB_GAMESCOPE_ARGS="-f -w 3840 -h 2160 -r 180"
SCB_AUTO_RES=0
SCB_AUTO_HDR=0
SCB_AUTO_VRR=0
